[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path  = "cache"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
roax = "https://devrpc.roax.net"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
